replicaCount: 2
image:
  repository: nginx
  tag: latest
  pullPolicy: Always
  namespace: newapp

application:
  track: stable
  tier: web

resources:
  requests:
    cpu: "0.5"
    memory: "1G"
  limits:
    cpu: "1"
    memory: "1G"

ingress:
  enabled: false

service:
  enabled: true
